CubeX/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CubeX.Models
{
    public class ShoppingCart
    {
        [Required]
        public string ID { get; set; }

        //[DataType(DataType.Currency, ErrorMessage = "Value must be a Currency ex. R20")]
        [Required]
        public double Sum { get; set; }

        public string ApplicationUserID { get; set; }


        public virtual ICollection<CartItem> Items { get; set; }
    }
}

CubeX/Controllers/OrderController.cs
using CubeX.Keys;
using CubeX.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace CubeX.Controllers
{
    public class OrderController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Order
        // TODO : Add Admin roles to this action
        public async Task<ActionResult> Index()
        {
            var currentUserId = User.Identity.GetUserId();

            if (User.IsInRole("Admin")){
                var orders = db.Orders.Include(o => o.User).Include(o => o.Items);
                return View(await orders.ToListAsync());
            }
            else
            {
                var orders = db.Orders
                    .Include(o => o.User)
                    .Include(o => o.Items)
                    .Where(x => x.UserID == currentUserId);
                return View(await orders.ToListAsync());
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Filter(string date)
        {
            DateTime filterDate = DateTime.Parse(date);
            ViewBag.Date = filterDate;

            var orders = db.Orders.Include(o => o.User).Include(o => o.Items)/*.Where(x => x.OrderDate.Date == filterDate)*/;
            return View("Index", await orders.ToListAsync());
        }

        // GET: Order/Details/5
        public async Task<ActionResult> Details()
        {

            string userId = User.Identity.GetUserId();

            var userOrders = await db.Orders
                .Include(order => order.Items)
                .Where(order => order.UserID == userId).ToListAsync();

            if (userOrders == null || userOrders.Count() < 1)
            {
                return View();
            }

            return View(userOrders);
        }


        public async Task<ActionResult> Delete(string id, string returnUrl)
        {
            string userId = User.Identity.GetUserId();

            Order order = await db.Orders
                .Include(ord => ord.User)
                .Include(ord => ord.Items)
                .Where(ord => ord.ID == id && ord.UserID == userId)
                .SingleOrDefaultAsync();

            List<CartItem> items = order.Items.ToList();

            items.ForEach(itm =>
            {
                itm.OrderID = null;
                db.Entry(itm).State = EntityState.Modified;
            });


            db.Orders.Remove(order);
            await db.SaveChangesAsync();

            return RedirectToLocalAction(returnUrl);
        }

        private ActionResult RedirectToLocalAction(string returnUrl)
        {
            if (returnUrl != null)
            {
                if (Url.IsLocalUrl(returnUrl))
                {       // If returnUrl is Local, then goto it
                    return Redirect(returnUrl);
                }
                else
                {   // If not, then return an Error View with a message in the ViewBag
                    ViewBag.ErrorMessage = "The return Url did not originate from our Server";
                    return View("Error");
                }
            }

            return RedirectToAction("Details");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CubeX/Controllers/ShoppingCartController.cs
using CubeX.Keys;
using CubeX.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Net;
using System.Net.Mail;

namespace CubeX.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();



        // GET: ShoppingCart/Details/5

        public ActionResult Details()
        {

            ApplicationUser user = GetUser();

            bool userHasOrder = db.Orders
                .Where(order => order.UserID == user.Id).Count() > 0;

            if (userHasOrder)
            {
                ViewBag.HasOrder = true;
            }

            ShoppingCart shoppingCart = user.ShoppingCart;

            // The shoppingCart will always be null when it is Empty because it's instance is deleted when it is empty
            if (shoppingCart == null)
            {
                // The view will tell the user that there is no item in the Cart
                return View();
            }

            return View(shoppingCart.Items);
        }



        // GET: ShoppingCart/Edit/5
        public async Task<ActionResult> Edit(string cartItemId, string returnUrl)
        {
            if (cartItemId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var cartItem = await db.CartItems.Where(c => c.ID == cartItemId).SingleOrDefaultAsync();

            if (cartItem == null)
            {
                return HttpNotFound();
            }

            if (returnUrl != null)
            {
                ViewBag.ReturnUrl = returnUrl;
            }
            return View(cartItem);
        }

        // POST: ShoppingCart/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(string ID, string returnUrl)
        {

            CartItem cartItem = db.CartItems.Find(ID);

            if (TryUpdateModel(cartItem, new string[] { "Quantity" }))
            {
                db.Entry(cartItem).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToLocalAction(returnUrl);
            }

            return View(cartItem);
        }

        // GET: ShoppingCart/Remove/id
        public async Task<ActionResult> Remove(string cartItemId, string returnUrl)
        {
            if (cartItemId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            string userId = User.Identity.GetUserId();

            var item = await db.CartItems.FindAsync(cartItemId);
            var cart = await db.ShoppingCarts
                .Where(shoppingCart => shoppingCart.ApplicationUserID == userId)
                .SingleOrDefaultAsync();


            if (item == null || cart == null)
            {
                return HttpNotFound();
            }

            try
            {
                db.Entry(item).State = EntityState.Deleted;

                await db.SaveChangesAsync();
            }
            catch (DbException ex)
            {
                Console.WriteLine(ex.ToString());
                ViewBag.ErrorMessage = "There was an error item was not successfully removed, please try again...";
                return View("Details", cart.Items.ToList());
            }

            ViewBag.Message = "Item Removed.";

            // If there is no more item, then delete the ShoppingCart instance from the database
            if (cart.Items.Count == 0)
            {
                bool isDeleted = DeleteShoppingCart(cart);
                if (isDeleted)
                {
                    return RedirectToAction("All", "Home");
                }
            }


            return RedirectToLocalAction(returnUrl);
        }

        public ActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Checkout([Bind(Include = "Destination")] Order order)
        {
            if (ModelState.IsValid)
            {
                string userId = User.Identity.GetUserId();

                ApplicationUser user = db.Users
                    .Include(usr => usr.ShoppingCart)
                    .Include(usr => usr.ShoppingCart.Items)
                    .Where(usr => usr.Id == userId)
                    .SingleOrDefault();

                ShoppingCart cart = user.ShoppingCart;

                if (cart == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                order.ID = GetNewUid();
                order.TotalAmount = cart.Sum;
                order.UserID = user.Id;
                order.OrderDate = DateTime.Now;

                SendEmail(order, cart, user);

                // TODO set all cartItems order id to the new order entity
                cart.Items.ToList().ForEach(cartItem =>
                {
                    cartItem.ShoppingCartID = null;
                    cartItem.OrderID = order.ID;
                    db.Entry(cartItem).State = EntityState.Modified;
                });

                // Remove user's ShoppingCart
                user.ShoppingCartID = null;
                db.Entry(user).State = EntityState.Modified;
                db.Entry(cart).State = EntityState.Deleted;

                try
                {
                    db.Orders.Add(order);
                    db.SaveChanges();

                    return View("CheckoutConfirmed");
                }
                catch (DbUpdateException ex)
                {
                    Console.WriteLine(ex.ToString());
                    return RedirectToAction("Checkout");
                }
            }
            return View();
        }

        public void SendEmail(Order order, ShoppingCart cart, ApplicationUser user)
        {
            string orderItems = "";
            foreach (var item in cart.Items.ToList())
            {
                orderItems += $"\t Item: {item.Name} | Price: {item.Price.ToString("C")} | Quantity: {item.Quantity} \n";
            }


            string fullName = user.FirstName + " " + user.Surname;
            string orderMessage =
                $"Hello, {fullName}! \n\n" +
                $"You have made an order with DUT Rendezvous Restaurant. \n\n" +
                $"Your order details are as follows: \n" +
                $"{orderItems} \n" +
                $"Date: {order.OrderDate.ToLongDateString()} \n" +
                $"Time: {order.OrderDate.ToShortTimeString()} \n" +
                $"Total: {order.TotalAmount.ToString("C")} \n\n" +
                $"Thank you for ordering with DUT Rendezvous Restaurant :)";

            //SendEmail
            var senderEmail = new MailAddress("dutrendezvous@gmail.com", "Rendezvous Restaurant");
            var recieverMail = new MailAddress(user.UserName, fullName);
            var password = "RendezvousDUT123";
            var sub = $"New Order #{order.ID.Substring(0, 5)}!";
            var body = orderMessage;

            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(senderEmail.Address, password)
            };
            using (var mess = new MailMessage(senderEmail, recieverMail)
            {
                Subject = sub,
                Body = body
            })
            {
                smtp.Send(mess);
            }
        }

        // Helpers
        private bool DeleteShoppingCart(ShoppingCart cart)
        {
            ApplicationUser user = GetUser();
            user.ShoppingCartID = null;
            db.Entry(cart).State = EntityState.Deleted;
            db.Entry(user).State = EntityState.Modified;

            int rowsAffected = db.SaveChanges();

            return rowsAffected > 0;

        }

        private List<FoodItem> GetFoodItems()
        {
            List<FoodItem> foodItems = db.FoodItems.Include(f => f.Category)
                 .Where(f => f.Discriminator == Discriminators.FoodItem)
                 .ToList();

            return FilterFoodItems(foodItems);
        }

        private List<FoodItem> FilterFoodItems(ICollection<FoodItem> foodItemsList)
        {
            if (User.Identity.IsAuthenticated == false)
            {
                return foodItemsList.ToList();
            }

            Dictionary<string, FoodItem> foodItems = foodItemsList.ToDictionary(fList => fList.Name);
            // Filter it with items in the Cart

            string userId = User.Identity.GetUserId();
            var cart = db.ShoppingCarts.Include(shoppingCart => shoppingCart.Items)
                .Where(s => s.ApplicationUserID == userId)
                .SingleOrDefault();

            if (cart != null)
            {
                List<CartItem> cartItems = cart.Items.ToList();

                cartItems.ForEach(cartItem =>
                {
                    if (foodItems.ContainsKey(cartItem.Name))
                    {
                        // Disable the item
                        var foodItem = foodItems[cartItem.Name];
                        foodItem.isEnabled = false;
                        foodItem.CartItemId = cartItem.ID;

                    }
                });
            }

            return foodItems.Select(f => f.Value).ToList();
        }

CubeX/Views/ShoppingCart/Checkout.cshtml
@model CubeX.Models.Order

@{
    ViewBag.Title = "Checkout";
}

<h2>Checkout</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Complete your Order</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

            <div class="form-group">
                @Html.LabelFor(model => model.Destination, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Destination, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Destination, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
            
        </div>
    }

<div>
    @Html.ActionLink("Go to Cart", "Details", null,new { @class = "btn btn-primary" })
</div>

CubeX/Views/ShoppingCart/CheckoutConfirmed.cshtml
@{
    ViewBag.Title = "Purchase Successful";
}

<div style="display:flex; justify-content:center; align-items:center; "><span style="color:lightgreen;  padding:25px; transform:scale(2.5)" class="glyphicon glyphicon-ok"></span><div style="padding:5px; font-size:2rem;" > Purchase Successful...</div></div>

<p>You will be redirected in 3 seconds... If not, click @Html.ActionLink("here","Details", "Order", null, null)</p>

@MyHelpers.RedirectBackToUrl("/Order/Details", 3)

CubeX/Views/ShoppingCart/Details.cshtml
@model ICollection<CubeX.Models.CartItem>

@{
    ViewBag.Title = "Details";
}

<h2>Shopping Cart</h2> 

@if (ViewBag.Message != null)
{
    <p class="text-center text-success">@(ViewBag.Message as string)</p>
}
else
{
    <p class="text-center text-danger">@(ViewBag.ErrorMessage as string)</p>
}

<div>
    <h4>Items</h4>
    
    <hr />
    <table class="table table-striped table-responsive" >
        <tr>
            <th>
                Name
            </th>
            
            <th>
                Price
            </th>
            <th>
                Quantity
            </th>
            <th></th>
        </tr>

        @if (Model != null && Model.Count > 0)
        {
            foreach (var cartItem in Model)
            {
                <tr>
                    <td>
                        @cartItem.Name
                    </td>
                    
                    <td>
                        @cartItem.Price
                    </td>
                    <td>
                        @cartItem.Quantity
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "ShoppingCart", new { cartItemId = cartItem.ID, returnUrl = Url.Action() },new { @class = "btn btn-primary" }) |
                        @Html.ActionLink("Remove", "Remove", "ShoppingCart", new { cartItemId = cartItem.ID, returnUrl = Url.Action() }, new { @class = "btn btn-danger" })
                    </td>
                </tr>
            }

            @Html.ActionLink("Checkout", "Checkout", null, new { @class = "btn btn-success btn-lg", id = "checkoutBtn" })

            
        }
        else
        {
            <tr class="text-center"><td colspan="3"><h4>You do not have any item in your Cart</h4> </td> </tr>
        }
    </table>
</div>

    @if (ViewBag.HasOrder != null)
    {
        @Html.ActionLink("Orders", "Details", "Order", null, new { @class = "btn btn-default btn-lg", id = "ordersBtn" });

    }

CubeX/Views/ShoppingCart/Edit.cshtml
@model CubeX.Models.CartItem

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cart Item</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        <input type="hidden" name"returnUrl" value="@(ViewBag.ReturnUrl)" />
        <dl>
            <dt> @Html.LabelFor(model => model.Name)</dt>
            <dd>@Html.DisplayFor(model => model.Name)</dd>
        </dl>

        <div class="form-group">
            <div class="col-md-10">
                @Html.DisplayNameFor(model => model.Quantity)
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
        </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>