CubeX/Controllers/TableDetailController.cs
using CubeX.Extensions;
using CubeX.Models;
using CubeX.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CubeX.Controllers
{
    public class TableDetailController : Controller
    {
        private ApplicationDbContext db;

        public TableDetailController()
        {
            db = ApplicationDbContext.Create();
        }

        public ActionResult Book(string search = null)
        {
            var thumbnails = new List<ThumbnailModel>().GetBookThumbnail(ApplicationDbContext.Create(), search);
            var count = thumbnails.Count() / 4;

            var model = new List<ThumbnailBoxViewModel>();

            for (int i = 0; i <= count; i++)
            {
                model.Add(new ThumbnailBoxViewModel
                {
                    Thumbnails = thumbnails.Skip(i * 2).Take(2)
                });
            }


            return View(model);
        }


        // GET: BookDetail
        public ActionResult Index(int id)
        {
            var userid = User.Identity.GetUserId();
            var user = db.Users.FirstOrDefault(u => u.Id == userid);

            var bookModel = db.Tables.SingleOrDefault(b => b.Id == id);

            //var rentalPrice = 0.0;
            //var oneMonthRental = 0.0;
            //var sixMonthRental = 0.0;
            //var rentalCount = 0;

            //if (userid != null && !User.IsInRole(SD.AdminUserRole))
            //{
            //    var chargeRate = from u in db.Users
            //                     join m in db.MembershipTypes on u.MembershipTypeId equals m.Id
            //                     where u.Id.Equals(userid)
            //                     select new { m.ChargeRateOneMonth, m.ChargeRateSixMonth, u.RentalCount };

            //    oneMonthRental = Convert.ToDouble(bookModel.Price) * Convert.ToDouble(chargeRate.ToList()[0].ChargeRateOneMonth) / 100;
            //    sixMonthRental = Convert.ToDouble(bookModel.Price) * Convert.ToDouble(chargeRate.ToList()[0].ChargeRateSixMonth) / 100;
            //    rentalCount = Convert.ToInt32(chargeRate.ToList()[0].RentalCount);
            //}

            TableRentalViewModel model = new TableRentalViewModel
            {
                TableId = bookModel.Id,
                Avaibility = bookModel.Avaibility,
                Description = bookModel.Description,
                Image = bookModel.Image,
                Name = bookModel.Name,
                UserId = userid,

            };

            return View(model);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
        }
    }
}

CubeX/Views/TableDetail/Book.cshtml
@model IEnumerable<CubeX.ViewModels.ThumbnailBoxViewModel>

@{ ViewBag.Title = "Book a Table"; }

@using (Html.BeginForm("Book", "TableDetail", FormMethod.Get))
{

<br />
                <div class="row">
                    <div class="pull-right" style="padding-right:15px;">
                        <button type="submit" value="Search" class="btn btn-sm btn-primary">
                            <span class="glyphicon glyphicon-search"></span>Search
                        </button>
                    </div>

                    <div class="pull-right">
                        @Html.Editor("search", new { htmlAttributes = new { @class = "form-control input-sm" } })
                    </div>

                </div>

                                <br />}
<div class="row">
    @foreach (var area in Model)
    {
@Html.Partial("_ThumbnailAreaPartial", area)}
</div>

CubeX/Views/TableDetail/Index.cshtml
@model CubeX.ViewModels.TableRentalViewModel
@using CubeX.Utilities

@{ ViewBag.Title = "Index";

    }

@using (Html.BeginForm("Reserve", "TableBook"))
{
@Html.AntiForgeryToken();

    <br /><br />
<div class="row">
    @* Table Image *@
    <div class="col-sm-3 col-xs-4 image-book">
        <img class="thumbnail-img" src="data:image;base64,@System.Convert.ToBase64String(Model.Image)" alt="" style="width:100%;height:auto;padding:10px;" />
    </div>


    @* Book Details *@
    <div class="col-sm-6 col-xs-8 content-book-main">
        <div class="content-book-title-author">
            <h2><b>@Model.Name (@Model.Avaibility tables left)</b></h2>
            <h5>Rendezvous Restaurant</h5>
        </div>
        <div>
            <br />
            <span>@Html.Raw(Model.Description)</span>
        </div><br />
    </div>


    @* Table details *@
<div class="col-sm-3 col-xs-12 content-book-product-details">

    <label>Select your booking date: </label><br />
    @Html.EditorFor(model => model.BookingDate, new { htmlAttributes = new { @class = "form-control" } })
    <span style="font-size:12px;">Reserve quickly before your slot disappears<br /><br /></span>

    <label>Select your booking time: </label><br />
    @Html.EditorFor(model => model.BookingTime, new { htmlAttributes = new { @class = "form-control" } })
    <span style="font-size:12px;">We're avaible between 10am and 3pm<br /><br /></span>

    <label>How many people are coming: </label><br />
    @Html.EditorFor(model => model.Seats, new { htmlAttributes = new { @class = "form-control" } })
    <span style="font-size:12px;">Maximum 10 people per booking<br /><br /></span>

    @if (User.IsInRole(SD.EndUserRole))
    {
        if (Model.Avaibility == 0)
        {
            <button type="submit" class="btn btn-danger" disabled="disabled">
                <span class="glyphicon glyphicon-thumbs-down"></span>&nbsp;No tables left to book
            </button>
        }
        else
        {
            <button type="submit" class="btn btn-primary">
                <span class="glyphicon glyphicon-thumbs-up"></span>&nbsp;Reserve
            </button>
        }
    }
    else
    {
        <button type="submit" class="btn btn-danger" disabled="disabled">
            <span class="glyphicon glyphicon-thumbs-down"></span>&nbsp;Login to Reserve
        </button>
    }

    <label style="color: red"> @ViewBag.Errors </label>
    <br /><br />



    @Html.HiddenFor(m => m.TableId)

</div>
</div>}