CubeX/ViewModels/TableViewModel.cs
using CubeX.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CubeX.ViewModels
{
    public class TableViewModel
    {
        public Table Table { get; set; }
    }
}

CubeX/Controllers/TableController.cs
using CubeX.Models;
using CubeX.Utilities;
using CubeX.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CubeX.Controllers
{
    [Authorize(Roles = SD.AdminUserRole)]
    public class TableController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        // GET: Table
        public ActionResult Index()
        {
            var tables = db.Tables.ToList();
            return View(tables);
        }


        // GET: Table/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Table table = db.Tables.Find(id);
            if (table == null)
            {
                return HttpNotFound();
            }

            var model = new TableViewModel
            {
                Table = table
            };
            return View(model);
        }

        // GET: Table/Create
        public ActionResult Create()
        {
            var model = new TableViewModel
            {
            };
            return View(model);
        }

        // POST: Table/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TableViewModel tableVM, HttpPostedFileBase file)
        {
            var table = new Table
            {
                Avaibility = tableVM.Table.Avaibility,
                Description = tableVM.Table.Description,
                //Image = tableVM.Table.Image,
                Name = tableVM.Table.Name,
            };
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    table.Image = ConvertToBytes(file);
                }

                db.Tables.Add(table);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tableVM);
        }

        public byte[] ConvertToBytes(HttpPostedFileBase image)
        {
            byte[] imageBytes = null;
            BinaryReader reader = new BinaryReader(image.InputStream);
            imageBytes = reader.ReadBytes((int)image.ContentLength);
            return imageBytes;
        }

        // GET: Table/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Table table = db.Tables.Find(id);
            if (table == null)
            {
                return HttpNotFound();
            }

            var model = new TableViewModel
            {
                Table = table
            };
            return View(model);
        }

        // POST: Table/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(TableViewModel tableVM)
        {
            var table = new Table
            {
                Id = tableVM.Table.Id,
                Avaibility = tableVM.Table.Avaibility,
                Description = tableVM.Table.Description,
                Image = tableVM.Table.Image,
                Name = tableVM.Table.Name
            };
            if (ModelState.IsValid)
            {
                db.Entry(table).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tableVM);
        }

        // GET: Table/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Table table = db.Tables.Find(id);
            if (table == null)
            {
                return HttpNotFound();
            }
            var model = new TableViewModel
            {
                Table = table
            };
            return View(model);
        }

        // POST: Table/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Table table = db.Tables.Find(id);
            db.Tables.Remove(table);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CubeX/Views/Table/Create.cshtml
@model CubeX.ViewModels.TableViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm("Create", "Table", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h3>Create Table</h3>
        <hr />
        <div class="form-border">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.Table.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Table.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Table.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Table.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                   @Html.TextAreaFor(model => model.Table.Description, new { @class = "form-control", style = "height:250px;" })
                    @Html.ValidationMessageFor(model => model.Table.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Table.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="file" />
                    @Html.ValidationMessageFor(model => model.Table.Image, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Table.Avaibility, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Table.Avaibility, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Table.Avaibility, "", new { @class = "text-danger" })
                </div>
            </div>

        </div>
        <br />
        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Create" class="btn btn-success btn-sm" />
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </div>
}

CubeX/Views/Table/Delete.cshtml
@model CubeX.ViewModels.TableViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h3>Delete Table</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Table.Id)
        <fieldset disabled>
            <div class="row" style="border:1px solid #bbb9b9; border-radius:5px;padding-top:25px;">
                <div class="col-sm-10">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Table.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Table.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Table.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Table.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Table.Description, new { @class = "form-control", style = "height:250px;" })
                            @Html.ValidationMessageFor(model => model.Table.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Table.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Table.Image, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Table.Image, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Table.Avaibility, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Table.Avaibility, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Table.Avaibility, "", new { @class = "text-danger" })
                        </div>
                    </div>

                </div>
                <div class="col-sm-2">
                    @*<div>
                        <img src="@Model.Table.ImageUrl" alt="" style="width:100%; height:auto" />
                    </div>*@
                </div>
            </div>
        </fieldset>
        <br />
        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Delete" class="btn btn-danger btn-sm" />
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </div>
}

CubeX/Views/Table/Details.cshtml
@model CubeX.ViewModels.TableViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="form-horizontal">
    <h3>Table Details</h3>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Table.Id)
    <fieldset disabled>
        <div class="row" style="border:1px solid #bbb9b9; border-radius:5px;padding-top:25px;">
            <div class="col-sm-10">

                <div class="form-group">
                    @Html.LabelFor(model => model.Table.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Table.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Table.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Table.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Table.Description, new { @class = "form-control",enabled="false", style = "height:250px;" })
                        @Html.ValidationMessageFor(model => model.Table.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Table.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Table.Image, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Table.Image, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Table.Avaibility, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Table.Avaibility, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Table.Avaibility, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            @*<div class="col-sm-2">
                <div>
                    <img src="@Model.Table.ImageUrl" alt="" style="width:100%; height:auto" />
                </div>
            </div>*@
        </div>
    </fieldset>
    <br />
    <div class="form-group">
        <div class="col-md-10">
            @Html.ActionLink("Edit", "Edit", new { id = Model.Table.Id }) |
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>

CubeX/Views/Table/Edit.cshtml
@model CubeX.ViewModels.TableViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h3>Edit Table</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Table.Id)
        <div class="row" style="border:1px solid #bbb9b9; border-radius:5px;padding-top:25px;">
            <div class="col-sm-10">

                <div class="form-group">
                    @Html.LabelFor(model => model.Table.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Table.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Table.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Table.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model=>model.Table.Description, new { @class="form-control",style="height:250px;" })
                        @Html.ValidationMessageFor(model => model.Table.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Table.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Table.Image, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Table.Image, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Table.Avaibility, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Table.Avaibility, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Table.Avaibility, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>
            @*<div class="col-sm-2">
                <div>
                    <img src="@Model.Table.ImageUrl" alt="" style="width:100%; height:auto" />
                </div>
            </div>*@
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Save" class="btn btn-success btn-sm" />
                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div>
        </div>
    </div>
}

CubeX/Views/Table/Index.cshtml
@model IEnumerable<CubeX.Models.Table>
@using CubeX.Models
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Manage Tables</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-condensed table-hover">
    <tr class="table-header">
        
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Avaibility)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th></th><th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Avaibility)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            <img src="data:image;base64,@System.Convert.ToBase64String(item.Image)" width="80" height="80" />
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>